Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [72]:
import numpy as np

In [68]:
x = int(input('Введите число\n'))
a = np.arange(0, x)
text = a[::-1]
print(text)

Введите число
10
[9 8 7 6 5 4 3 2 1 0]


Задание 2 Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [66]:
z = int(input('Введите число: '))
print(np.diag(np.arange(z-1, -1, -1), k=0))
print('Сумма по диагонали:', sum(sum(np.diag(np.arange(z-1, -1, -1), k=0))))


Введите число: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма по диагонали: 45


Задание 3
Решите систему уравнений:

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [76]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])


Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [89]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное расстояние между этим пользователем и 
всеми пользователями из массива user_stats

In [90]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

max_cosine = 0
for i, user in enumerate(users_stats):
    print(i+1, cosine(user, next_user_stats))
    if cosine(user, next_user_stats) > max_cosine:
        max_cosine = cosine(user, next_user_stats)
        max_id = i +1
print('Максимально похожий пользователь c ID:', max_id)

1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0
Максимально похожий пользователь c ID: 8
